### ISSUE TITLE
MTGA opens but with cursor on black screen; no progress

### ISSUE THREAD

**Issue by fernplant** [DevRayy/HeyMacArena#2]
Unfortunately this trick may no longer work. For me I just get a black screen. Any other workaround you've found? Thanks

**Comment by DevRayy** [comment]
Confirmed. The game does not respect resolution changes and also does not work without Epic Games Store.

Unfortunately I don't know any workarounds - I play mostly through GeForce Now and I think its the best way to play the game on Mac for now.
